config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "home#index"

  resources :athletes
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/athlete.rb
class Athlete < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :gender, inclusion: { in: %w(K M) }
  validates :birthdate, presence: true
  validates :city, presence: true
  validates :route_id, presence: true
  validates :phone, presence: true, format: { with: /\A\+?\d+\z/,
    message: "tylko cyfry, opcjonalnie poprzedzone plusem" }
  validates :email, presence: true,
    format: {
      with: /\A([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)\z/,
      message: "tylko poprawny adres email"
    }
  validates :terms_accepted, acceptance: true
  validates :gdpr_accepted, acceptance: true
  validates :event_id, presence: true

  belongs_to :route
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :event_date, presence: true
  validates :last_entries_date, presence: true

  has_many :routes
  has_many :athletes

  scope :active, -> do
    where("last_entries_date >= ?", Date.today)
    .order(:event_date)
  end
end

app/models/route.rb
class Route < ApplicationRecord
  validates :name, presence: true
  validates :distance, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 100 }
  validates :event_id, presence: true

  belongs_to :event
  has_many :athletes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  layout "dusiolek", only: [:index,:show]

  before_action :set_athlete, only: [:show]

  # GET /athletes
  # GET /athletes.json
  def index
    @event = Event.find(params[:event_id])

  end

  # GET /athletes/1
  # GET /athletes/1.json
  def show
    @event = @athlete.event
    
  end

  # GET /athletes/new
  def new
    @event = Event.find(params[:event_id])
    @routes = @event.routes
    @athlete = Athlete.new(event_id: @event.id)
  end

  # POST /athletes
  # POST /athletes.json
  def create
    @athlete = Athlete.new(athlete_params)
    @event = @athlete.event
    @routes = @event.routes
    respond_to do |format|
      if @athlete.save
        format.html { redirect_to @athlete, notice: 'Zgłoszenie zostało przyjęteTT' }
        format.json { render :show, status: :created, location: @athlete }
      else
        format.html { render :new }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_athlete
      @athlete = Athlete.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def athlete_params
      params.require(:athlete).permit(:first_name, :last_name, :gender, :birthdate, :city, :route_id, :phone,
                                      :team, :email, :terms_accepted, :gdpr_accepted, :event_id)


    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "dusiolek"

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/views/athletes/_form.html.erb
<%= form_with(model: athlete, local: true) do |form| %>
  <% if athlete.errors.any? %>
   <div id="error_explanation">
      <h2><%= "Zgłoszenie nie może być przyjęte. Ilość błędów: #{athlete.errors.count}" %></h2>
      <ul>
       <% athlete.errors.full_messages.each do |message| %>
               <li><%= message %></li>
             <% end %>

             </ul>

   </div>
  <% end %>

 <%= form.hidden_field(:event_id) %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>

  </div>
  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    Płeć
    <br></br>
    <%= form.radio_button(:gender, 'K') %>
    <%= form.label :gender_k, "Kobieta" %>
    <%= form.radio_button(:gender, 'M') %>
    <%= form.label :gender_m, "Mężczyzna" %>
  </div>

  <div class="field">
    <%= form.label :birthdate %>
    <%= form.date_select(:birthdate,  { start_year: 1920, use_month_numbers: true, order: [:day, :month, :year]}, { class: 'date' } ) %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
       Trasa
       <br></br>
    <% routes.each do |route| %>
        <%= form.radio_button(:route_id, route.id) %>
        <%= form.label "route_id_#{route.id}", route.name %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :team %>
    <%= form.text_field :team %>
  </div>

  <div class="field">
    <%= form.label :Email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.check_box :terms_accepted %>
    <%= form.label :terms_accepted, "zapoznałem się z Regulaminem i akceptuję jego postanowienia" %>
  </div>

    <div class="field">
      <%= form.check_box :gdpr_accepted %>
      <%= form.label :gdpr_accepted, "Wyrażam zgodę na wykorzystanie i przetwarzanie moich danych osobowych" %>
    </div>


  <div class="actions">
      <%= form.submit :"  Wyślij zgłoszenie" %>

  </div>
  </body>
  </html>

<% end %>

app/views/athletes/_form0.html.erb
<%= simple_form_for  @athlete do |f| %>
  <% if @athlete.errors.any? %>
 <div id="error_explanation">
 <h2><%=  "Zgłoszenie nie może być przyjęte. Ilość błędów: #{athlete.errors.count}" %></h2>
<ul>
 <% athlete.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>

       </ul>
 </div>
 <% end %>
 <%=f.input(:event_id, as: :hidden) %>

 <div>
   <%=f.input :first_name %>
   </div>
   <%=f.input :last_name %>
   <div>
   <%=f.label :gender  %>
   <%= f.radio_button(:gender, 'K', required: true) %> Kobieta
   <%= f.radio_button(:gender, 'M', required: true) %> Mężczyzna
   </div>
   <%=f.label :birthdate %>
   <%=f.date_select(:birthdate, start_year: 1920, use_month_numbers: true, order: [:day, :month, :year]) %>
<div>
<%=f.input :city %>
</div>

<div class="field"> <%= f.label :route_id %>
  <% routes.each do |route| %>
    <%=f.radio_button(:route_id, route.id, required: true) %>
    <%= route.name %>
  <% end %>
</div>
<%= f.input :phone %>
<%=f.input :team %>
 <%= f.input :email, :label => "Email" %>
<div class="field">
  <%= f.check_box :terms_accepted , required: true %>
  <%= f.label "zapoznałem się z Regulaminem i akceptuję jego postanowienia" %>
</div>

  <div class="field">
    <%= f.check_box :gdpr_accepted , required: true %>
    <%= f.label "Wyrażam zgodę na wykorzystanie i przetwarzanie moich danych osobowych" %>
  </div>

<div class="actions">
<%= f.button :submit %>
</div>

  <% end %>

app/views/athletes/_form1.html.erb
<%= form_with(model: athlete, local: true) do |form| %>
  <% if athlete.errors.any? %>
   <div id="error_explanation">
      <h2><%= "Zgłoszenie nie może być przyjęte. Ilość błędów: #{athlete.errors.count}" %></h2>
      <ul>
       <% athlete.errors.full_messages.each do |message| %>
               <li><%= message %></li>
             <% end %>

             </ul>

   </div>
  <% end %>

 <%= form.hidden_field(:event_id) %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>

  </div>
  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    Płeć
    <br></br>
    <%= form.radio_button(:gender, 'K') %>
    <%= form.label :gender_k, "Kobieta" %>
    <%= form.radio_button(:gender, 'M') %>
    <%= form.label :gender_m, "Mężczyzna" %>
  </div>

  <div class="field">
    <%= form.label :birthdate %>
    <%= form.date_select(:birthdate,  { start_year: 1920, use_month_numbers: true, order: [:day, :month, :year]}, { class: 'date' } ) %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
       Trasa
       <br></br>
    <% routes.each do |route| %>
        <%= form.radio_button(:route_id, route.id) %>
        <%= form.label "route_id_#{route.id}", route.name %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :team %>
    <%= form.text_field :team %>
  </div>

  <div class="field">
    <%= form.label :Email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.check_box :terms_accepted %>
    <%= form.label :terms_accepted, "zapoznałem się z Regulaminem i akceptuję jego postanowienia" %>
  </div>

    <div class="field">
      <%= form.check_box :gdpr_accepted %>
      <%= form.label :gdpr_accepted, "Wyrażam zgodę na wykorzystanie i przetwarzanie moich danych osobowych" %>
    </div>


  <div class="actions">
      <%= form.submit :"  Wyślij zgłoszenie" %>

  </div>
  </body>
  </html>

<% end %>

app/views/athletes/edit.html.erb
<h1>Editing Athlete</h1>

<%= render 'form', athlete: @athlete %>

<%= link_to 'Show', @athlete %> |
<%= link_to 'Back', athletes_path %>

app/views/athletes/form1.html.erb
<%= simple_form_for  @athlete do |f| %>

  <% if @athlete.errors.any? %>
 <div id="error_explanation">
 <h2><%=  "Zgłoszenie nie może być przyjęte. Ilość błędów: #{athlete.errors.count}" %></h2>
<ul>
 <% athlete.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>

       </ul>
 </div>
 <% end %>
 <%=f.input(:event_id, as: :hidden) %>

 <div>
   <%=f.input :first_name, required: false %>
   </div>
   <%=f.input :last_name %>
   <div>
   <%=f.label :gender  %>
   <%= f.radio_button(:gender, 'K', required: true) %> Kobieta
   <%= f.radio_button(:gender, 'M', required: true) %> Mężczyzna
   </div>
   <%=f.label :birthdate %>
   <%=f.date_select(:birthdate, start_year: 1920, use_month_numbers: true, order: [:day, :month, :year]) %>
<div>
<%=f.input :city %>
</div>

<div class="field"> <%= f.label :route_id %>
  <% routes.each do |route| %>
    <%=f.radio_button(:route_id, route.id, required: true) %>
    <%= route.name %>
  <% end %>
</div>
<%= f.input :phone %>
<%=f.input :team %>
 <%= f.input :email, :label => "Email" %>
 <br></br>
 <div class="field">
  <%= f.check_box :terms_accepted , required: true %>
  <%= f.label "zapoznałem się z Regulaminem i akceptuję jego postanowienia" %>
  <%= f.check_box :gdpr_accepted , required: true %>
    <%= f.label "Wyrażam zgodę na wykorzystanie i przetwarzanie moich danych osobowych" %>
</div>

<div class="actions">
<%= f.button :submit,'Wyślij zgłoszenie' %>
</div>

  <% end %>

app/views/athletes/index.html.erb
<h1>Lista startowa</h1>
<h2><%= @event.name %></h2>
<% @event.routes.each do |route|  %>

<h3><%= route.name %></h3>
<table border="1px" class="start_list">
<thead>
    <tr style='background:#ddd;'>
      <td>Numer
        </td>
      <td><span class='caps'>Imię</td>
      <td>Nazwisko</td>
      <td>Miejscowość</td>
      <td>Drużyna</td>
    </tr>

</thead>
  <tbody>
    <% route.athletes.each_with_index do |athlete, i| %>
      <tr>
        <td><%= i + 1 %></td>
        <td><%= athlete.first_name %></td>
        <td><%= athlete.last_name %></td>
        <td><%= athlete.city %></td>
        <td><%= athlete.team %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>

<%= link_to "Strona główna", root_path %>

app/views/athletes/new.html.erb
<h1>Formularz zgłoszeniowy</h1>
<h2><%= @event.name %></h2>
<h2><%= I18n.l( @event.event_date) %></h2>

<%= render 'form', athlete: @athlete, routes: @routes %>
<%= link_to 'Strona główna', root_path %>

app/views/athletes/show.html.erb
<section  class="wrapper">
<div class="inner">
<p id="notice"><%= notice %></p>
<h2>Zgłoszenie zostało przyjęte</h2>
<h1><%= @event.name %></h1>
<h5>Do zobaczenia <%= I18n.l( @event.event_date) %></h5>



<!-- Content -->
<table border="1px">
  <tbody>
<div class="content">
<tr style='background:#ddd;'>
  <td>Imię i Nazwisko
    </td>
    <td><%= @athlete.first_name %>
    <%= @athlete.last_name %></td>
  </tr>

<tr>
<td>Płeć</td>
<td>  <%= @athlete.gender %></td>
</tr>
<tr>
<td>Data urodzenia:</td>
<td>  <%= @athlete.birthdate %></td>
</tr>
<tr>
<td>Miejscowość:</td>
<td>  <%= @athlete.city %></td>
  </tr>
<tr>
<td>Trasa:</td>
<td>  <%= @athlete.route.name %></td>
  </tr>
  <tr>
  <td>Numer telefonu:</td>
  <td>  <%= @athlete.phone %></td>
    </tr>
    <tr>
    <td>Drużyna:</td>
    <td>  <%= @athlete.team %></td>
      </tr>
      <tr>
      <td>Email:</td>
      <td>  <%= @athlete.email %></td>
        </tr>
</tbody>
</table>

<%= link_to 'Dalej', root_path %>
</div>
</section>

app/views/home/index.html.erb
<!-- Banner -->
  <section id="banner">
    <article>
      <img src="images/zdj9.jpg" alt="" />
      <div class="inner">
        <h2><a href="#">DUSIOŁEK GÓRSKI </a></h2>
      </div>
    </article>
    <article>
      <img src="images/zdj10.jpg" alt="" />
      <div class="inner">
        <h2><a href="#">DUSIOŁEK GÓRSKI</a></h2>
      </div>
    </article>
    <article>
      <img src="images/zdj11.jpg"  alt="" />
      <div class="inner">
        <h2><a href="#">DUSIOŁEK GÓRSKI</a></h2>
      </div>
    </article>
  </section>

<!-- One -->
  <section id="one" class="wrapper major-pad">
    <div class="inner">
      <section class="spotlight">
        <div class="content">
          <h2>Podstawowe informacje</h2>
          <dl>
          <dt>Dusiołek Górski:</dt>
          <dd>Rekreacyjny rajd turystyczny</dd>
          <dt>Okolica:</dt>
            <dd>Beskid Wyspowy</dd>
<dt>Start i meta:</dt><dd> Wiśniowa koło Dobczyc</dd>
<dt>Termin:</dt><dd> 18 maja 2019, godzina startu: 8:00</dd>
<dt>Dystans:<dt>
  </ dl>

  <dd>
<ul>
<li>
Dziecięcy: ok. 7 km</li>
<li>  Klasyczny ok. 35 km
</li>
</dd>
</ul>


<dt>Czas:</dt><dd> 12 godzin</dd>
<dt>Cel:</dt><dd> Dobra zabawa na świeżym powietrzu!</dd>
<dt>Nagrody:</dt><dd> Satysfakcja i słoik dżemu (wiśniowego!)</dd>

</dl>
  <dl>
        </div>
        <span class="image"><img src="images/zdj4.jpg" alt="" /></span>
      </section>
    </div>
  </section>

<!-- Two -->
  <section id="two" class="wrapper content-pad">
    <div class="inner">
      <div class="features">
        <section class="content">
          <span class="icon-wrapper major"><span class="icon fa-list-alt"></span></span>
          <h3>Zgłoszenia</h3>
            <% Event.active.each do |event| %>
              <%= link_to(event.name, new_athlete_path(event_id: event.id),class: "button" ) %>
              <br></br>
            <% end %>
        </section>
        <section class="content">
          <span class="icon-wrapper major"><span class="icon fa-list-ol"></span></span>
          <h3>Listy startowe</h3>
          <% Event.all.order(:event_date).each do |event| %>
            <%= link_to(event.name, athletes_path(event_id: event.id), class: "button" ) %>
            <br></br>
          <% end %>
        </section>
        <section class="content">
          <span class="icon-wrapper major"><span class="icon fa-cloud"></span></span>
          <h3>Magnis curabitur</h3>
          <p>Duis vulputate sit amet metus quis facilisis. Sed dapibus neque erat fringilla tincidunt. Nullam sapien et sapien, iaculis ac varius ultrices nec metus. Aenean ultricies magna.</p>
        </section>
      </div>
    </div>
  </section>

<!-- Three -->
  <section id="three" class="wrapper style2">
    <div class="inner">
      <h2>Dusiołek</h2>
      <div class="posts">
        <section class="post">
          <span class="image"><img src="images/zdj1.jpg" alt="" /></span>
          <div class="content">
            <h3>Aktualności</h3>
            <p>17.05.2019</p>

<p>Mamy zamknięte listy startowe, 217 osób na trasie klasycznej i 22 uczestników trasy dziecięcej. Słoneczko świeci, widzimy się jutro z rana. Jak ktoś na trasę klasyczną to zapraszamy jutro od 6:17.</p>
            <ul class="actions">
              <li><a href="#" class="button">More</a></li>
            </ul>
          </div>
        </section>
        <section class="post">
          <span class="image"><img src="images/zdj8.jpg" alt="" /></span>
          <div class="content">
            <h3>Z albumu Dusiołka</h3>
            <p>Damy słoik dżemu panu zmęczonemu ...
Na mecie XV Dusiołka Górskiego, maj 2018 </p>
            <ul class="actions">
              <li><a href="#" class="button">More</a></li>
            </ul>
          </div>
        </section>
        <section class="post">
          <span class="image"><img src="images/zdj3.jpg" alt="" /></span>
          <div class="content">
            <h3>Warto zajrzeć</h3>
            <p>

  <li>  Poprzednia, archiwalna wersja strony Dusiołka Górskiego (2011-18)</li>
  <li>  Pogoda w Wiśniowej</li>
    <li>Zdjęcia ze ścieżek, którymi przebiega lub maszeruje a niekiedy człapie Dusiołek</li>
    <li>Centrum Turystyki Aktywnej BAJERSPORT</li>

</p>
            <ul class="actions">
              <a href="#" class="button">More</a>
            </ul>
          </div>
        </section>
        <section class="post">
          <span class="image"><img src="images/pic04.jpg" alt="" /></span>
          <div class="content">
            <h3>Regulamin</h3>


              <br></br>

            <ul class="actions">
              <li><a href="/regulamin" class="button">More</a></li>
            </ul>
          </div>
        </section>
        <section class="post">
          <span class="image"><img src="images/pic05.jpg" alt="" /></span>
          <div class="content">
            <h3>Program rajdu</h3>
            <p>Libero condimentum, vehicula sem vel, mattis mauris. Nullam lacinia sit amet felis vel vestibulum. Morbi in aliquam est. Aenean dapibus porttitor nulla ultrices venenatis.</p>
            <ul class="actions">
              <li><a href="#" class="button">More</a></li>
            </ul>
          </div>
        </section>
        <section class="post">
          <span class="image"><img src="images/pic06.jpg" alt="" /></span>
          <div class="content">
            <h3>Vestibulum placerat</h3>
            <p>Tristique tellus et ullamcorper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent mauris risus, pellentesque eu leo non, tincidunt.</p>
            <ul class="actions">
              <li><a href="#" class="button">More</a></li>
            </ul>
          </div>
        </section>
      </div>
    </div>
  </section>

<!-- Contact -->
  <section id="contact" class="wrapper split">
    <div class="inner">
      <section>
        <h2>Napisz do nas wiadomość</h2>
        <form method="post" action="#">
          <div class="row gtr-uniform">
            <div class="col-6 col-12-large col-6-medium col-12-xsmall">
              <label for="name">Imię</label>
              <input type="text" name="name" id="name" />
            </div>
            <div class="col-6 col-12-large col-6-medium col-12-xsmall">
              <label for="email">Email</label>
              <input type="email" name="email" id="email" />
            </div>
            <div class="col-12">
              <label for="message">Treść wiadomości</label>
              <textarea name="message" id="message" rows="5"></textarea>
            </div>
            <div class="col-12">
              <ul class="actions">
                <li><input type="submit" value="Wyślij wiadomość" class="primary" /></li>
                <li><input type="reset" value="Nowa wiadomość" /></li>
              </ul>
            </div>
          </div>
        </form>
      </section>
      <section>
        <h2>Inne sposoby kontaktu</h2>
        <ul class="bulleted-icons">
          <li>
            <span class="icon-wrapper"><span class="icon fa-envelope"></span></span>
            <h3>Email</h3>
            <p>biuro@bajersport.pl</p>
          </li>
          <li>
            <span class="icon-wrapper"><span class="icon fa-phone"></span></span>
            <h3>Numer telefonu</h3>
            <p>606 258 725</p>
          </li>
          <li>
            <span class="icon-wrapper"><span class="icon fa-facebook"></span></span>
            <h3>Facebook</h3>
            <%=link_to 'BAJERSPORT' , "https://www.facebook.com/pg/Bajer-Sport-Centrum-Turystyki-Aktywnej-263197297046508/about/?ref=page_internal"  %>
          </li>
          <li>
            <span class="icon-wrapper"><span class="icon fa-home"></span></span>
            <h3>Mailing Address</h3>
            <p>ul. Piłsudskiego 48<br />
        32-400 Myslenice    <br />
            Polska
            </p>
          </li>
        </ul>
      </section>
    </div>
  </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Orient</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/dusiolek.html.erb
<!DOCTYPE HTML>
<!--
	Slate by Pixelarity
	pixelarity.com | hello@pixelarity.com
	License: pixelarity.com/license
-->
<html>
	<head>
		<title>Orient</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="/assets/css/main.css" />
		<noscript><link rel="stylesheet" href="/assets/css/noscript.css" /></noscript>
	</head>
	<body class="is-preload">
		<!-- Header -->
			<header id="header" class="alt">
				<h1><a href="/">ORIENT <span> BajerSport</span></a></h1>
				<nav id="nav">
					<ul>
						<li><a href="/">Strona główna</a></li>
					</ul>
				</nav>
			</header>
      <%= yield %>
		<!-- Footer -->
			<footer id="footer">
				<div class="inner">
					<p class="copyright">&copy; Untitled Corp Marcin Bajer & Jan Sochacki</p>
					<ul class="menu">
						<li><a href="#">Terms<span> of Use</span></a></li>
						<li><a href="#">Privacy<span> Policy</span></a></li>
						<li><a href="#">Legal<span> Information</span></a></li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="/assets/js/jquery.min.js"></script>
			<script src="/assets/js/jquery.dropotron.min.js"></script>
			<script src="/assets/js/jquery.scrollex.min.js"></script>
			<script src="/assets/js/browser.min.js"></script>
			<script src="/assets/js/breakpoints.min.js"></script>
			<script src="/assets/js/util.js"></script>
			<script src="/assets/js/main.js"></script>

	</body>
</html>